# Generated by Django 6.0.2 on 2026-04-08 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VysledekTestu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum testu"),
                ),
                ("sifra_zadani", models.TextField(verbose_name="Zašifrovaný text")),
                (
                    "sifra_typ",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Druh šifry"
                    ),
                ),
                (
                    "sifra_spravne_zadani",
                    models.TextField(verbose_name="Správné řešení"),
                ),
                (
                    "sifra_odpoved_uzivatele",
                    models.TextField(blank=True, verbose_name="Odpověď uživatele"),
                ),
                (
                    "sifra_spravne",
                    models.BooleanField(default=False, verbose_name="Šifra správně?"),
                ),
                (
                    "uzel_nazev",
                    models.CharField(max_length=100, verbose_name="Název uzlu"),
                ),
                (
                    "uzel_hotovo",
                    models.BooleanField(default=False, verbose_name="Uzel uvázán"),
                ),
                (
                    "body_celkem",
                    models.IntegerField(default=0, verbose_name="Body celkem"),
                ),
                (
                    "uzivatel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Výsledek testu",
                "verbose_name_plural": "Výsledky testů",
            },
        ),
    ]
