# Generated by Django 6.0.2 on 2026-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabulkaSlov",
            fields=[
                ("TextId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Text pro šifrování"),
                ),
            ],
            options={
                "verbose_name": "Tabulka slov",
                "verbose_name_plural": "Tabulka slov",
            },
        ),
    ]
