# Generated by Django 6.0.2 on 2026-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vysledektestu",
            name="sifra_typ",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Druh šifry"
            ),
        ),
    ]
