# Generated by Django 6.0.2 on 2026-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vysledektestu",
            old_name="sifra_odpoved",
            new_name="sifra_odpoved_uzivatele",
        ),
        migrations.RemoveField(
            model_name="vysledektestu",
            name="sifra_bod",
        ),
        migrations.AddField(
            model_name="vysledektestu",
            name="sifra_spravne_zadani",
            field=models.TextField(default=0, verbose_name="Správné řešení"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vysledektestu",
            name="sifra_typ",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Druh šifry"
            ),
        ),
        migrations.AlterField(
            model_name="vysledektestu",
            name="sifra_spravne",
            field=models.BooleanField(default=False, verbose_name="Šifra správně?"),
        ),
    ]
