"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hbg1=cl$@*jb0%d*j)fc#6cfv1_wvkw75k!x$onfhca)0v2-$m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'main',
    'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Detekce prostředí Renderu
RENDER_DB_URL = os.environ.get('DATABASE_URL')

# CHCEŠ DATABÁZI SCHVÁLNĚ VYPNUT? Můžeš změnit na True nebo smazat DATABASE_URL v Renderu
DISABLE_DATABASE = False 

if DISABLE_DATABASE or not RENDER_DB_URL:
    # -------------------------------------------------------------
    # BEZDATABÁZOVÝ REŽIM (Nouzový fallback)
    # -------------------------------------------------------------
    print("\n" + "="*60)
    print("  VAROVÁNÍ: Produkční databáze na Renderu byla ODPOJENA!")
    print("  Aplikace běží v BEZDATABÁZOVÉM režimu (In-Memory RAM).")
    print("="*60 + "\n")
    
    # Django vyžaduje konfiguraci, podhodíme mu dočasnou paměť RAM
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
    
    # Automaticky vytvoříme prázdné tabulky v paměti RAM, aby web nespadl na chybách
    import django
    django.setup()
    from django.core.management import call_command
    try:
        call_command('migrate', interactive=False)
        print("[OK] Tabulky pro nouzový režim byly vytvořeny v paměti.")
    except Exception as e:
        print(f"[CHYBA] Nepodařilo se inicializovat nouzovou DB: {e}")

else:
    # -------------------------------------------------------------
    # STANDARDNÍ REŽIM (Propojení na Render PostgreSQL / MySQL)
    # -------------------------------------------------------------
    DATABASES = {
        'default': dj_database_url.config(
            default=RENDER_DB_URL,
            conn_max_age=600
        )
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
